name: Run Tests and Comment on PR

on:
  pull_request:

permissions:
  pull-requests: write  # Required to comment on the pull request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests and capture output
        id: run-tests
        run: |
          set +e
          OUTPUT=$(./mvnw test 2>&1)
          echo "$OUTPUT"
          echo "output<<EOF" >> $GITHUB_OUTPUT
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "exitcode=$?" >> $GITHUB_OUTPUT

      - name: Comment test results on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `${{ steps.run-tests.outputs.output }}`;
            const statusEmoji = `${{ steps.run-tests.outputs.exitcode }}` === '0' ? '✅' : '❌';
            const truncated = output.length > 65000 ? output.slice(-65000) : output;
            
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${statusEmoji} *Test results for commit \`${context.payload.pull_request.head.sha.substring(0, 7)}\`*\n\n\`\`\`\n${truncated}\n\`\`\``
            });
