name: Run Tests and Comment on PR

on:
  pull_request:

permissions:
  pull-requests: write  # Required to comment on the pull request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests and save output to file
        id: run-tests
        run: |
          set +e
          mvn test 2>&1 | tee test-output.txt
          echo "exitcode=$?" >> $GITHUB_OUTPUT

      - name: Comment test summary on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('test-output.txt', 'utf8');
            
            // Search for the last line that matches the summary pattern
            const summaryRegex = /Tests run:\s*(\d+),\s*Failures:\s*(\d+),\s*Errors:\s*(\d+),\s*Skipped:\s*(\d+)/g;
            let match, lastMatch;
            while ((match = summaryRegex.exec(output)) !== null) {
              lastMatch = match;
            }
            
            let summary = '⚠️ Test summary not found.';
            if (lastMatch) {
              const [, run, failures, errors, skipped] = lastMatch;
              const failedCount = parseInt(failures) + parseInt(errors);
              const statusEmoji = failedCount === 0 ? '✅' : '❌';
              summary = `${statusEmoji} *Tests run: ${run}, Failed: ${failures}, Errors: ${errors}, Skipped: ${skipped}*`;
            }
            
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });
